apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hello-world-app
manifests:
  rawYaml:
    - manifests/dev.yaml
deploy:
  cloudrun: {}
profiles:
  - name: dev
    manifests:
      rawYaml:
        - manifests/dev.yaml
  - name: staging
    manifests:
      rawYaml:
        - manifests/staging.yaml
  - name: prod
    manifests:
      rawYaml:
        - manifests/prod.yaml
